language: python
python:
  - "2.7"
  - "3.5"
  - "pypy3.5"
  - "nightly"
script:
  - pytest --cov=scorpy
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
after_success:
  - coveralls
