language: python
python:
  - "2.7"
  - "3.5"
  - "pypy3.5"
  - "nightly"
script:
  - pytest --cov=scorpy
install:
  - pip install python-coveralls
  - pip install coverage
after_success:
  - coveralls
